title: Settings
data:
  site_name: 'The Status Code'
  personality: casual
  show_signup: true
  social:
    -
      id: Z7KbvUxu
      name: Twitter
      url: 'https://twitter.com/statamic'
      icon: site/social-icons/twitter.svg
    -
      id: GJRPN7Tt
      name: Github
      url: 'https://github.com/statamic/starter-kit-starters-creek'
      icon: site/social-icons/github.svg
    -
      id: in9FDrxu
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
